steps:
 gctsDeploy:
  client: '100'
  host: "https://sapsp2.camelot-idpro.de:44300"
  abapCredentialsId: 'ABAP_SP2'
  repository: "karanchopras-workbench"
  remoteRepositoryURL: "https://github.com/karanchopras/workbench"
  role: 'SOURCE'
  vSID: 'GIT'
  verbose: true
  type: 'GITHUB'
