general:
  steps:
    gctsDeploy:
          host: "http://saps4s.camelot-idpro.de:44300"
          client: "100"
          abapCredentialsId: "S4S_KCHO"
          repository: "karanchopras-workbench"
          remoteRepositoryURL: "https://github.com/karanchopras/workbench"
          role: "SOURCE"
          vSID: "GIT"
          verbose: true
          type: "GITHUB"
          rollback: false
 stages:       
    Build:
      kanikoExecute: true
    Acceptance:
      kubernetesDeploy: true
    Release:
      kubernetesDeploy: true
