PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !P_SEL MODULE %_P_SEL .

FIELD !P_CYC MODULE %_P_CYC .

FIELD !P_STDT MODULE %_P_STDT .

CHAIN.
  FIELD P_SEL .
  FIELD P_CYC .
  FIELD P_STDT .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.